"$schema" = "schemas/schema.json"

[default]
description = "Default permissions for the plugin"
permissions = ["allow-is-exist","allow-is-dir", "allow-is-file", "allow-size", "allow-name", "allow-full-name", "allow-extname", "allow-metadata", "allow-open"]
